### ISSUE TITLE
Logo contribution 

### ISSUE THREAD

**Issue by Batarian711** [ethanhuang13/ladybug#13]
Hi. I am a graphic designer. I volunteer to design a logo for open source projects. I can design it for you to use it in the readme file. What dou you say?

**Comment by ethanhuang13** [comment]
Interesting. Did you saw the app icon? What do you think about it? https://github.com/ethanhuang13/ladybug/tree/master/Ladybug/Resources/Assets.xcassets/AppIcon.appiconset

**Comment by ethanhuang13** [comment]
Also, what open source projects do you contribute to? Any ways I can see those logos?

**Comment by Batarian711** [comment]
My github profile visit please :)

**Comment by Batarian711** [comment]
Do you want me to send you a sample drawing?

**Comment by Batarian711** [comment]
I designed an iconic logo about the name of the application. Is there anything you want to add? What do you think? 
![ladybug](https://user-images.githubusercontent.com/41051393/42722975-c69276e8-875d-11e8-890b-bea2debfb35d.jpg)

**Comment by ethanhuang13** [comment]
Thanks, but I have to say, no thanks. It's just not my style.

**Comment by Batarian711** [comment]
Okey thank you
