### ISSUE TITLE
[Suggestion] Add case-sensitive warning on import from Open Radar

### ISSUE THREAD

**Issue by zntfdr** [ethanhuang13/ladybug#15]
Hi @ethanhuang13 thank you so much for this utility app, I love it! 😍 

A small UX feedback:
As OpenRadar APIs are case sensitive, I had to try multiple times before succeeding in importing my radars because of the case sensitive nature. 
Therefore, if I had registered my google email as **T**his**I**s**M**y**E**mail@gmail.com, that exact format is the only one that is accepted by OpenRadar Apis. If I'd input **t**his**i**s**m**y**e**mail@gmail.com or any other combination of lower/upper case letters, it would fail.

Beside that, everything is awesome! 🌈 

Please have a nice day,
fz

**Comment by ethanhuang13** [comment]
Interesting, I didn't know that. Will add a warning. Thanks for the suggestion.

(By the way, I saved my email addresses in AddressBook, so iOS keyboard will suggest them above the keyboard. Or use iOS Text Replacement feature for commonly used emails.)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by zntfdr** [comment]
Thank you for the prompt response!

Yes, I have "@@" which transforms to my email as I type, but the email I put in there is all lowercase:
when I registered to Gmail well over 10 years ago, I registered with some letters uppercase 😅

**Comment by zntfdr** [comment]
谢谢你 @ethanhuang13 🙌🏻
